
version: "3.4"

services:
  hometg:
    build:
      context: .
      dockerfile: HomeTG.API/Dockerfile
    pull_policy: build
    container_name: hometg-api
    ports:
      - "5234:80"
    volumes:
      - /config/hometg:/home/root/.local/share/hometg/DB/hometg
    environment:
      ASPNETCORE_ENVIRONMENT: linux
      ConnectionStrings__Postgres: "Host=database;Username=hometg;Password=supersecretpassword;Database=hometg_db"
      provider: Postgres
    depends_on:
      - database
    networks:
      - public
      - private
    restart: unless-stopped

  hometg-react:
    build:
      context: .
      dockerfile: HomeTG.React/Dockerfile
    pull_policy: build
    container_name: hometg-react
    ports:
      - "5235:3000"
    environment:
      REACT_APP_API_URL: "http://hometg:80"
      WDS_SOCKET_PORT: 0
    depends_on:
      - hometg
    networks:
      - public
      - private
    restart: unless-stopped

  database:
    image: postgres:16.3
    container_name: hometg-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hometg
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: hometg_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private
    restart: unless-stopped

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  postgres-data: